spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/jrtp
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
